title:				Projective-C
description:		Collection of FizzBuzz Xcode projects

me:					Harshita Chandra
myurl:				http://github.com/thelastjedi

baseurl:			"" # the subpath of your site, e.g. /blog/
url:				http://projectivec.github.io
email:				projectivec@outlook.com

permalink:			/:title
highlighter:		rouge
markdown:			kramdown

showsocial:			true

google_analytics:	UA-52347455-3
